on:
  push:
  workflow_dispatch:



env:
  FILE: kleur-4.1.4.tgz

jobs:
  download:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        file: [kleur-4.1.4.tgz]
        try: [1,2,3,4,5,6,7,8,9,11,12,13,14,15,16]

    steps:
      - run: curl https://registry.yarnpkg.com/kleur/-/${{ matrix.file }} --output ${{ matrix.file }}
